# Generated by Django 5.1 on 2024-10-09 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("middle_name", models.CharField(blank=True, max_length=30)),
                ("surname", models.CharField(blank=True, max_length=30)),
                ("phone_no", models.CharField(blank=True, max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-created_at"],
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session", models.CharField(max_length=225)),
                ("resource", models.CharField(max_length=225)),
                ("action", models.CharField(max_length=225)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("M", "Male"), ("F", "Female")], null=True
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("IDCARD", "Identity Card"),
                            ("PASSPORT", "Passport"),
                            ("ALIENID", "Alien ID"),
                        ]
                    ),
                ),
                (
                    "document_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("document_expiry_date", models.DateField(blank=True, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("blockchain_id", models.CharField(blank=True, max_length=100)),
                (
                    "profile_photo",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                (
                    "oauth_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GOOGLE", "Google"),
                            ("FACEBOOK", "Facebook"),
                            ("GITHUB", "Github"),
                            ("TWITTER", "Twitter"),
                            ("APPLE", "Apple"),
                            ("NONE", "None"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["uuid"], name="uuidx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone_no"], name="phonex"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="emailx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="timex"),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("first_name", "surname", "email")},
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["session"], name="sessionx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["resource"], name="resourcex"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["gender"], name="genderx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["dob"], name="dobx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["blockchain_id"], name="blockidx"),
        ),
    ]
