# Generated by Django 5.1 on 2024-09-17 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session", models.CharField(max_length=225)),
                ("resource", models.CharField(max_length=225)),
                ("action", models.CharField(max_length=225)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(choices=[("M", "Male"), ("F", "Female")])),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("IDCARD", "Identity Card"),
                            ("PASSPORT", "Passport"),
                            ("ALIENID", "Alien ID"),
                        ]
                    ),
                ),
                (
                    "document_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("document_expiry_date", models.DateField(blank=True, null=True)),
                ("phone_no", models.CharField(blank=True, max_length=20, unique=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("blockchain_id", models.CharField(blank=True, max_length=100)),
                (
                    "oauth_provider",
                    models.CharField(
                        choices=[
                            ("GOOGLE", "Google"),
                            ("FACEBOOK", "Facebook"),
                            ("GITHUB", "Github"),
                            ("TWITTER", "Twitter"),
                            ("APPLE", "Apple"),
                            ("NONE", "None"),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "ordering": ["-created_at"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.RenameField(
            model_name="user",
            old_name="id",
            new_name="uuid",
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("first_name", "surname", "email")},
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["uuid"], name="uuidx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="emailx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="timex"),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="UserActivity",
        ),
        migrations.RemoveField(
            model_name="user",
            name="blockchain_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="user",
            name="document_expiry_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="document_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="id_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_no",
        ),
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["session"], name="sessionx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["resource"], name="resourcex"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["gender"], name="genderx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["dob"], name="dobx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["blockchain_id"], name="blockidx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["phone_no"], name="phonex"),
        ),
    ]
