# Generated by Django 5.1 on 2024-10-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blockchain_id",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="document_expiry_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="oauth_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GOOGLE", "Google"),
                    ("FACEBOOK", "Facebook"),
                    ("GITHUB", "Github"),
                    ("TWITTER", "Twitter"),
                    ("APPLE", "Apple"),
                    ("NONE", "None"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_no",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
