# Generated by Django 5.1 on 2024-10-12 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_initial"),
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="elections.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="ballot",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="elections.poll",
            ),
        ),
        migrations.AlterField(
            model_name="ballot",
            name="voter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="organizations.member",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="elections.poll",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="elections.election",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="organizations.position",
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="body",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="organizations.body",
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="elections.election",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="elections.candidate",
            ),
        ),
    ]
